# Generated by Django 5.2 on 2025-08-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_role_remove_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('clinic', 'Clinic'), ('seller', 'Seller'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
