# Generated by Django 5.1.3 on 2025-10-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('clinic', 'Clinic'), ('seller', 'Seller'), ('admin', 'Admin'), ('receptionist', 'Receptionist')], default='user', max_length=20),
        ),
    ]
