# Generated by Django 5.1.3 on 2025-10-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('clinic', 'Clinic'), ('seller', 'Seller'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
