# Generated by Django 5.1.3 on 2025-10-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_clinic',
            field=models.BooleanField(default=False),
        ),
    ]
