# Generated by Django 5.1.3 on 2025-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='facebook_page',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Page'),
        ),
    ]
